package seed

import (
	"github.com/isd-sgcu/johnjud-backend/src/app/model/pet"
	constant "github.com/isd-sgcu/johnjud-backend/src/constant/pet"
)

var pets = []pet.Pet{
	{
		Type:         "cat",
		Species:      "",
		Name:         "เต้าเจี้ยว",
		Birthdate:    "",
		Gender:       constant.MALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ขี้อ้อน ชอบนั่งตัก ติดคน",
		Caption:      "สวัสดีฮะ ผมชื่อเต้าเจี้ยวเป็นแมวจากร้านข้าวมันไก่ เป็นพี่น้องซีอิ้ว เดิมผมอยู่กับคุณป้าร้านข้าวมันไก่ มีคุณป้าคอยให้อาหาร กินอาหารเม็ดบ้าง เศษไก่ เศษข้าวบ้าง จนพี่ๆจากชมรมมาเจอและขอพาผมไปทำหมัน ตอนนี้ผมเลยได้มาอยู่ในชมรม รอใครสักคนมารับผมกลับบ้าน ผมกลัวพี่แมวตัวใหญ่ในชมรมนิดหน่อย ทำให้ไม่ค่อยได้เลยกับพี่ทีมงานเท่าที่ควร แต่จริงๆแล้วผมเป็นแมวขี้เล่นและขี้อ้อนมากนะ สนใจรับผมไปอยู่บ้านด้วยกันมั้ยครับ",
		Status:       constant.FINDHOME,
		IsSterile:    true,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "ซีอิ๊ว",
		Birthdate:    "",
		Gender:       constant.FEMALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ขี้อ้อน ขี้กลัว",
		Caption:      "หนูชื่อซีอิ๊ว ที่ได้ชื่อนี้เพราะหนูมาจากร้านข้าวมันไก่ ตอนแรกหนูมีคุณป้าร้านข้าวมันไก่คอยให้ข้าวให้น้ำ และให้ที่หลบรถและคนน่ากลัวอยู่หลังร้านของคุณป้า จนหนูถูกพามาทำหมันและได้มาอยู่ในชมรม หนูยังคงเป็นแมวขี้ระแวง ไว้ใจแค่เต้าเจี้ยวและพี่ทีมงานบ้างคน ถึงหนูจะขี้ระแวงแต่หนูก็ไม่เคยกัดหรือข่วนใคร ยิ่งกับคนที่หนูไว้ใจหนูจะขี้อ้อนมากๆเลยนะ อยากเล่นด้วยและอยากได้รับความรักอยู่ตลอด",
		Status:       constant.FINDHOME,
		IsSterile:    true,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "พัดพา",
		Birthdate:    "",
		Gender:       constant.FEMALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ติดคน ชอบคน ขี้อ้อนมาก ชอบนั่งตัก",
		Caption:      "ในวันที่ลมพัดแรงและฝนกำลังจะตกอย่างหนัก ผมแมวจรที่กำลังวิ่งหาที่หลบฝนอยู่ จนได้ไปหลบที่พุ่มไม้บริเวณคณะสัตวแพทย์ วันนั้นผมเตรียมใจแล้วว่าจะต้องโดนฝนและเปียกแน่ๆ กลายเป็นว่าวันนั้น ผมไม่ได้เปียกอย่างที่คาด เพราะมีพี่ชมรมคนนึงผ่านมาเห็นผม และอุ้มผมไปหลบฝน พร้อมกับโอบกอดผมเอาไว้อย่างอบอุ่น และเป็นสาเหตุที่ทำให้ผมได้ชื่อใหม่ว่า ’พัดพา’",
		Status:       constant.FINDHOME,
		IsSterile:    true,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "โอริโอ้",
		Birthdate:    "",
		Gender:       constant.MALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ซน เล่นแรง กอดได้",
		Caption:      "ผมชื่อโอริโอ้ เป็นแมวจากตลาดสามย่าน ผมเคยได้บ้านไปแล้ว แต่เนื่องจากเหตุผลจำเป็นทำให้คุณแม่คนเดิมของผมไม่สามารถดูแลผมต่อได้ ผมเลยต้องกลับมาอยู่ที่ชมรมอีกครั้ง ผมเป็นเด็กดีนะ ร่าเริง ขี้เล่น และแข็งแรงเหมือนแมวปกติทั่วไป ถึงจะเข้าใจแต่ก็อดเสียใจไม่ได้ที่ต้องกลับมาเป็นแมวไม่มีเจ้าของอีกครั้ง จะมีอีกมั้ยโอกาสครั้งที่2 ที่จะมีคนมาให้ความรักแมวดำตัวอ้วนๆตัวนี้",
		Status:       constant.FINDHOME,
		IsSterile:    true,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "แม่พลอย",
		Birthdate:    "",
		Gender:       constant.FEMALE,
		Color:        "",
		Pattern:      "",
		Habit:        "เข้ากับแมวตัวอื่นได้ดี เรียบร้อย",
		Caption:      "แม่พลอย แมวจรบริเวณสะพานลอยสยาม เดิมทีหนูเป็นแมวจรใช้ชีวิต หลบฝน หลบรถ และหากินเองข้างนอก จนวันหนึ่งต่อมก้นหนูอักเสบและเป็นแผล ทางชมรมจึงพาหนูมารักษาและหาหมอ  ปัจจุบันหนูหายดีแล้ว แต่เพราะระยะเวลาการรักษาที่นาน บวกกับมีแมวเจ้าถิ่นตัวใหม่ ทำให้หนูไม่สามารถกลับไปใช้ชีวิตที่เดิมได้อีกแล้ว ตอนนี้หนูชินที่จะอยู่ในห้อง เรียนรู้ที่จะมีความสุขกับการนอนบนผ้านิ่มๆ ฝนเล็บกับกล่องลัง และส่งสายตาอ้อนให้พี่ทีมงานลูบหัวในทุกๆวัน",
		Status:       constant.FINDHOME,
		IsSterile:    true,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "แมงมุม",
		Birthdate:    "",
		Gender:       constant.MALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ขี้เล่น ร่าเริง ชอบของเล่น",
		Caption:      "ผมเป็นลูกแมวที่ถูกช่วยมาจากบริเวณสยาม ที่ได้ชื่อว่าแมงมุมก็เพราะนิสัยที่ชอบนอนบนหลังคากระบะทรายและหลังคากรงของผม ตอนอยู่กับคนผมเป็นแมวขี้อ้อน และตอนอยู่กับเพื่อนๆแมวผมก็เป็นแมวขี้เล่น สดใส ซนตามวัย ตอนนี้เพื่อนแมวหลายตัวค่อยๆทยอยได้บ้านกันไป เหลือก็แต่ผมที่ยังคงนั่งนับวันรอ เมื่อไหร่นะจะมีคนมาหลงรักและพาผมไปอยู่ด้วยกันบ้าง",
		Status:       constant.FINDHOME,
		IsSterile:    false,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "ลูกหม่อน",
		Birthdate:    "",
		Gender:       constant.FEMALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ขี้อ้อนมาก ติดคน ชอบร้องเรียกคน ฉลาด ซนตามวัย",
		Caption:      "รอแคปชั่น",
		Status:       constant.FINDHOME,
		IsSterile:    false,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "ซาบะ",
		Birthdate:    "",
		Gender:       constant.FEMALE,
		Color:        "",
		Pattern:      "",
		Habit:        "เรียบร้อย นิ่ง ขี้อ้อน ไม่โวยวาย",
		Caption:      "รอแคปชั่น",
		Status:       constant.FINDHOME,
		IsSterile:    true,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "ทูน่า",
		Birthdate:    "",
		Gender:       constant.FEMALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ขี้อ้อนมากถึงมากที่สุด ขอให้ได้ถูคน เดินตามติดชิดเหมือนเงา ร้องจนกว่าจะได้แตะตัวคน เสียงน่ารักมาก",
		Caption:      "รอแคปชั่น",
		Status:       constant.FINDHOME,
		IsSterile:    false,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "มีจ้า",
		Birthdate:    "",
		Gender:       constant.MALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ขี้เล่น ขี้สงสัย ชอบกระโดด ทำหน้าตลกๆ",
		Caption:      "มีจ้าเป็นลูกแมวกำพร้าตัวคนเดียวติดมากับมอเตอร์ไซค์ จากนั้นได้รับความช่วยเหลือให้อยู่ในการดูแลจาก “แม่” มีคิ้ว ซึ่งทำหน้าที่เป็นคุณแม่บุญธรรมของมีจ้า ผ่านไปไม่นาน มีจ้าก็ได้มีพี่น้องชื่อ มะพร้าว และมะเฟือง แต่ภายหลัง ทั้งสามตัวป่วย เป็นโชคดีที่มีจ้าหายจากอาการป่วยมาได้ แต่แล้วโชคก็เล่นตลกร้ายกับมีจ้า เพราะทั้งมะพร้าวและมะเฟืองได้จากไปอย่างไม่มีวันกลับ ทำให้มีจ้าต้องกลับมาอยู่คนเดียวอีกครั้ง ระหว่างที่กำลังพักฟื้น หนูได้มีโอกาสพบเจอแมวอื่นมากมาย แต่ส่วนใหญ่ทุกคนก็ได้บ้านหมดแล้ว เหลือแต่หนูแล้วสิ แต่หนูก็จะรอ รอวันที่หนูจะไม่ต้องเหงาอีกแล้ว รอวันที่หนูได้รับความรัก ในชีวิตหนูมีช่วงเวลาให้ต้องอยู่คนเดียวมากมายเหลือเกิน หนูหวังว่าจะมีใครสักคนที่มาโอบกอดหนูไว้ มาพาหนูกลับบ้าน แล้วหนูจะไม่ต้องตัวคนเดียวอีก แต่เอ๊ะ! หนูได้ข่าวมาว่าพี่ๆในชมรมกำลังช่วยกันหาบ้านที่อบอุ่นให้กับหนู หนูดีใจและตื่นเต้นมากๆ ชักอดใจไม่ไหวที่จะสำรวจบ้านในอนาคตแล้วว",
		Status:       constant.ADOPTED,
		IsSterile:    false,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "หวานเจี๊ยบ",
		Birthdate:    "",
		Gender:       constant.FEMALE,
		Color:        "",
		Pattern:      "",
		Habit:        "แมวเด็กติดคน ชอบปีนขึ้นที่สูง ให้กระโดดขึ้นตักได้ ชอบเล่นซ่อนแอบแต่ก็วิ่งมาหาอยู่ดี",
		Caption:      "รอแคปชั่น",
		Status:       constant.FINDHOME,
		IsSterile:    false,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    true,
		Origin:       "club",
		Address:      "",
		Contact:      "",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "มะกอก & มะกรูด",
		Birthdate:    "",
		Gender:       constant.MALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ขี้เล่น สุขภาพแข็งแรงดี",
		Caption:      "มะกอกกระโดดไม่ค่อยได้ เพราะ เคยตกหลังคามาก่อน",
		Status:       constant.FINDHOME,
		IsSterile:    false,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    false,
		Origin:       "entrust",
		Address:      "ซอยราชครู ถ.พหลโยธิน พญาไท",
		Contact:      "เบอร์โทร 0863450127 , Line ID: pumviranee",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "น้องมอม",
		Birthdate:    "",
		Gender:       constant.FEMALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ขี้อ้อน ขี้กลัว",
		Caption:      "คาดว่าหลุดมา ก่อนหน้านี้มีคลอดลูกแล้ว 3 ตัว ลูกๆได้บ้านครบแล้ว เหลือแม่เหมียวที่ยังไม่มีคนรับเลี้ยง",
		Status:       constant.FINDHOME,
		IsSterile:    true,
		IsVaccinated: true,
		IsVisible:    true,
		IsClubPet:    false,
		Origin:       "entrust",
		Address:      "บางรัก",
		Contact:      "inbox โดยตรงที่ Noppawan Pleankhum",
		AdoptBy:      "",
	}, {
		Type:         "cat",
		Species:      "",
		Name:         "น้องเด็กหรือแมวเด็ก",
		Birthdate:    "",
		Gender:       constant.FEMALE,
		Color:        "",
		Pattern:      "",
		Habit:        "ไม่ได้ระบุมา",
		Caption:      "คาดว่าน้องน่าจะพลัดหลงกับแม่ ตอนฝนตกหนัก",
		Status:       constant.FINDHOME,
		IsSterile:    false,
		IsVaccinated: false,
		IsVisible:    true,
		IsClubPet:    false,
		Origin:       "entrust",
		Address:      "ราชเทวี",
		Contact:      "Line ID: @paboyababy , เบอร์โทร 0846145357",
		AdoptBy:      "",
	},
}
